import {useState,useEffect,createContext,useContext,ReactNode} from 'react';
import {Routes,Route,NavLink,Link,useNavigate,useParams} from 'react-router-dom';
import {BookOpen,Files,Search,Plus,ArrowUpRight,ArrowRight,Activity,ShieldCheck,Settings,HelpCircle,MessageSquare,Library,Menu,X,Sun,Moon,Upload,FileText,Link2,Check,Loader2,ChevronRight,Download} from 'lucide-react';
import {api,date} from './api';
import {HelpView} from './Help';

type Ctx={notify:(text:string,error?:boolean)=>void;refresh:()=>void;tick:number;add:()=>void};
export const Context=createContext<Ctx>({notify:()=>{},refresh:()=>{},tick:0,add:()=>{}});
export function useData(path:string){const {tick}=useContext(Context);const [data,setData]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{let active=true;api(path).then(d=>{if(active){setData(d);setError('')}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[path,tick]);return {data,error};}
export function ErrorBox({text}:{text:string}){return text?<div className="alert error" role="alert">{text}</div>:null}
export function Empty({icon,heading,children}:{icon:ReactNode;heading:string;children:ReactNode}){return <div className="empty"><span className="empty-icon">{icon}</span><h2>{heading}</h2>{children}</div>}
export function Badge({children}:{children:ReactNode}){return <span className={'badge '+String(children).toLowerCase().replaceAll('_','-')}>{String(children).replaceAll('_',' ')}</span>}
export function Heading({eyebrow,title,children,action}:{eyebrow:string;title:string;children?:ReactNode;action?:ReactNode}){return <header className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{children&&<p>{children}</p>}</div>{action}</header>}

function AddSource({close}:{close:()=>void}){
 const [tab,setTab]=useState('text'),[title,setTitle]=useState(''),[text,setText]=useState(''),[url,setURL]=useState(''),[file,setFile]=useState<File|null>(null),[compile,setCompile]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const {notify,refresh}=useContext(Context);const nav=useNavigate();
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let result;if(tab==='file'){const form=new FormData();form.append('file',file!);form.append('title',title);form.append('compile',String(compile));result=await api('/sources/files','POST',form)}else result=await api('/sources/'+tab,'POST',tab==='text'?{title,text,compile}:{title,url,compile});notify(result.source?.duplicate?'Source already preserved. Processing queued.':'Source added. Processing queued.');refresh();close();nav('/activity')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)},[close]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><div className="modal-title"><div><span className="eyebrow">GROW YOUR KNOWLEDGE</span><h2 id="add-title">Add a source</h2></div><button className="icon-button" onClick={close} aria-label="Close"><X size={20}/></button></div><div className="tabs">{[['text',FileText,'Paste text'],['file',Upload,'Upload file'],['url',Link2,'Webpage']].map(([id,Icon,label]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</div><form onSubmit={submit}><label>Source title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} required={tab==='text'} placeholder="Give this source a useful name"/></label>{tab==='text'?<label>Content<textarea rows={9} value={text} onChange={e=>setText(e.target.value)} required placeholder="Paste an article, notes, or a document. Original text is preserved."/></label>:tab==='url'?<label>Public webpage URL<input type="url" value={url} onChange={e=>setURL(e.target.value)} required placeholder="https://example.com/article"/></label>:<label className="upload-zone"><Upload/><strong>{file?.name||'Choose a document'}</strong><span>PDF, Markdown or TXT · up to 20 MiB by default</span><input type="file" accept=".pdf,.md,.txt" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label>}<label className="check-row"><input type="checkbox" checked={compile} onChange={e=>setCompile(e.target.checked)}/>Compile into the wiki after extraction</label><p className="small muted">Originals stay on your machine. AI processing sends selected text to your configured provider.</p><ErrorBox text={error}/><div className="modal-footer"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<Plus size={16}/>}Add source</button></div></form></section></div>
}

function Home(){const {data:status}=useData('/status');const {data:pages,error}=useData('/wiki');const {data:sources}=useData('/sources');const {add}=useContext(Context);return <><Heading eyebrow="YOUR PERSONAL KNOWLEDGE BASE" title="Knowledge, connected." action={<button className="button" onClick={add}><Plus size={17}/>Add source</button>}>A growing understanding of everything you collect.</Heading><div className="stats">{[['Wiki pages',status?.pages,BookOpen],['Preserved sources',status?.sources,Files],['Page revisions',status?.revisions,Activity],['Open review issues',status?.issues,ShieldCheck]].map(([label,n,Icon]:any)=><div className="stat" key={label}><div><span>{label}</span><strong>{n??'—'}</strong></div><Icon size={21}/></div>)}</div>{status&&!status.provider_ready&&<div className="setup-banner"><span className="banner-icon"><Settings size={20}/></span><div><strong>Connect a model to start compiling.</strong><p>Your library works locally. Choose a provider and model, then enable external models in Settings to turn sources into wiki pages.</p></div><Link className="text-link" to="/settings">Set up AI <ArrowRight size={16}/></Link></div>}<div className="section-title"><h2>Recently updated</h2><span className="muted small">Your evolving wiki</span></div><ErrorBox text={error}/>{pages?.length?<div className="page-list">{pages.slice(0,8).map((p:any)=>{const doc=JSON.parse(p.doc);return <Link className="page-row" key={p.id} to={'/wiki/'+p.id}><span className="document-icon"><BookOpen size={20}/></span><div className="grow"><h3>{p.title}</h3><p>{doc.blocks[0]?.content.slice(0,150)||p.reason}</p><div className="row-meta">{doc.tags.slice(0,3).map((t:string)=><span key={t}>#{t}</span>)}<span>{date(p.updated)}</span></div></div><ChevronRight size={18}/></Link>})}</div>:<Empty icon={<BookOpen size={30}/>} heading="Your next idea starts with a source."><p>Add something worth remembering. The compiler connects its evidence to concepts as your library grows.</p><button className="button" onClick={add}><Plus size={16}/>Add your first source</button><div className="flow"><span>Preserve sources</span><ArrowRight size={14}/><span>Connect concepts</span><ArrowRight size={14}/><span>Build understanding</span></div></Empty>}<div className="section-title"><h2>Recent sources</h2><Link to="/sources" className="text-link">View library <ArrowUpRight size={15}/></Link></div>{sources?.length?<div className="source-grid">{sources.slice(0,3).map((s:any)=><Link className="source-card" key={s.id} to={'/sources/'+s.id}><div><FileText size={19}/><Badge>{s.type}</Badge></div><h3>{s.title}</h3><p>{date(s.created)}</p><Badge>{s.status}</Badge></Link>)}</div>:<div className="quiet-empty"><Files size={19}/>No sources yet. Your originals will appear here.</div>}</>}

function SearchView(){const [query,setQuery]=useState('');const {data,error}=useData('/search?q='+encodeURIComponent(query));return <><Heading eyebrow="FIND THE CONNECTION" title="Search your knowledge"/><div className="search-large"><Search size={22}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search concepts, sources, and evidence…"/></div><ErrorBox text={error}/>{data?.map((r:any)=><Link key={r.id} className="page-row" to={(r.kind==='WIKI'?'/wiki/':'/sources/')+r.id}><div className="grow"><Badge>{r.kind}</Badge><h3>{r.title}</h3><p>{r.excerpt}</p></div><ChevronRight size={18}/></Link>)}{query&&data?.length===0&&<div className="quiet-empty">No matches. Try a different word or phrase.</div>}</>}

// Additional working views are loaded from a separate module to keep the shell focused.
import {SourcesView,SourceView,PageView,ActivityView,ResearchView,HealthView,SettingsView} from './views';
export default function App(){
 const [tick,setTick]=useState(0),[adding,setAdding]=useState(false),[toast,setToast]=useState<{text:string;error:boolean}|null>(null),[mobile,setMobile]=useState(false),[dark,setDark]=useState(localStorage.getItem('theme')==='dark');
 useEffect(()=>{const timer=setInterval(()=>setTick(n=>n+1),4000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 function notify(text:string,error=false){setToast({text,error});setTimeout(()=>setToast(null),7000)}
 const nav=[['/',BookOpen,'Wiki'],['/sources',Files,'Sources'],['/research',MessageSquare,'Research'],['/activity',Activity,'Activity'],['/health',ShieldCheck,'Wiki health']];
 return <Context.Provider value={{notify,refresh:()=>setTick(n=>n+1),tick,add:()=>setAdding(true)}}><div className="app"><aside className={'sidebar '+(mobile?'open':'')}><Link to="/" className="brand"><span><Library size={23}/></span><strong>Commonplace</strong></Link><div className="workspace-label">PERSONAL WORKSPACE</div><nav>{nav.map(([path,Icon,label]:any)=><NavLink key={path} to={path} end={path==='/'} onClick={()=>setMobile(false)}><Icon size={19}/>{label}</NavLink>)}</nav><button className="sidebar-add" onClick={()=>setAdding(true)}><Plus size={17}/>Add a source</button><div className="sidebar-bottom"><div className="local-note"><span className="local-mark"/><div><strong>Stored locally</strong><small>Your sources. Your knowledge.</small></div></div><NavLink to="/help" onClick={()=>setMobile(false)}><HelpCircle size={18}/>Quick Guide &amp; Help</NavLink><NavLink to="/settings" onClick={()=>setMobile(false)}><Settings size={18}/>Settings</NavLink></div></aside><div className="main-shell"><div className="topbar"><button className="icon-button mobile-menu" aria-label="Navigation" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><span className="breadcrumb">Workspace <ChevronRight size={13}/> Personal wiki</span><div className="topbar-actions"><Link to="/search" className="search-trigger"><Search size={16}/><span>Search knowledge</span></Link><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Toggle color theme">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><span className="avatar">You</span></div></div><main><Routes><Route path="/" element={<Home/>}/><Route path="/search" element={<SearchView/>}/><Route path="/sources" element={<SourcesView/>}/><Route path="/sources/:id" element={<SourceView/>}/><Route path="/wiki/:id" element={<PageView/>}/><Route path="/activity" element={<ActivityView/>}/><Route path="/research" element={<ResearchView/>}/><Route path="/health" element={<HealthView/>}/><Route path="/help" element={<HelpView/>}/><Route path="/settings" element={<SettingsView/>}/></Routes><footer>COMMONPLACE <span>Evidence preserved. Understanding evolves.</span></footer></main></div></div>{adding&&<AddSource close={()=>setAdding(false)}/>} {toast&&<div className={'toast '+(toast.error?'error':'')} role="status">{toast.error?<X size={18}/>:<Check size={18}/>} {toast.text}</div>}</Context.Provider>
}
