import {useRef,useState} from 'react';
import {api} from './api';
type Item={file:File;path:string;key:string;state:'pending'|'uploading'|'queued'|'failed'|'skipped';message:string};
export function FileUpload({busy,onBusy,onQueued,onClose,onActivity}:{busy:boolean;onBusy:(b:boolean)=>void;onQueued:()=>void;onClose:()=>void;onActivity:()=>void}){
 const [items,setItems]=useState<Item[]>([]),[compile,setCompile]=useState(true),[error,setError]=useState('');
 const stop=useRef(false),running=useRef(false),choice=useRef<boolean|null>(null);
 function select(files:FileList|null){if(!files)return;choice.current=null;setError('');setItems(Array.from(files).sort((a,b)=>(a.webkitRelativePath||a.name).localeCompare(b.webkitRelativePath||b.name,undefined,{numeric:true})).map(file=>{const path=file.webkitRelativePath||file.name,hidden=path.split('/').some(p=>p.startsWith('.')),supported=/\.(pdf|md|txt)$/i.test(file.name);return {file,path,key:crypto.randomUUID(),state:hidden||!supported?'skipped':'pending',message:hidden?'Hidden file or folder':!supported?'Unsupported file type':''}}))}
 function update(key:string,state:Item['state'],message:string){setItems(old=>old.map(i=>i.key===key?{...i,state,message}:i))}
 async function upload(){if(running.current)return;running.current=true;onBusy(true);stop.current=false;setError('');const mode=choice.current??compile;choice.current=mode;
 try{for(const item of items.filter(i=>i.state==='pending'||i.state==='failed')){if(stop.current)break;update(item.key,'uploading','Uploading…');try{const form=new FormData();form.append('file',item.file,item.file.name);form.append('title',item.path);form.append('compile',String(mode));const r=await api('/sources/files','POST',form,{'Idempotency-Key':item.key});update(item.key,'queued',r.source?.duplicate?'Already preserved · processing queued':'Uploaded · processing queued');onQueued()}catch(e){update(item.key,'failed',e instanceof Error?e.message:'Upload failed')}}}finally{running.current=false;onBusy(false)}}
 const queued=items.filter(i=>i.state==='queued').length,failed=items.filter(i=>i.state==='failed').length,pending=items.filter(i=>i.state==='pending').length,skipped=items.filter(i=>i.state==='skipped').length;
 return <div><div className="batch-pickers"><label>Choose files<input aria-label="Choose files" type="file" multiple accept=".pdf,.md,.txt" disabled={busy} onChange={e=>{select(e.target.files);e.target.value=''}}/></label><label>Choose folder<input aria-label="Choose folder" type="file" multiple {...{webkitdirectory:''}} disabled={busy} onChange={e=>{select(e.target.files);e.target.value=''}}/></label></div>
 <p className="small muted">PDF, Markdown and TXT. Folders include subfolders. Hidden and unsupported files are skipped. Choosing again replaces this list.</p>
 {items.length>0&&<><p className="batch-summary" role="status" aria-live="polite">{items.length} selected · {queued} queued · {pending} waiting · {failed} failed · {skipped} skipped</p><ul className="batch-files" aria-label="Selected files">{items.map(i=><li key={i.key}><div><strong>{i.path}</strong><small>{(i.file.size/1024).toFixed(1)} KiB · {i.message||'Ready to upload'}</small></div>{!busy&&i.state!=='queued'&&<button className="icon-button" aria-label={'Remove '+i.path} onClick={()=>setItems(old=>old.filter(x=>x.key!==i.key))}>×</button>}</li>)}</ul></>}
 <label className="check-row"><input type="checkbox" checked={compile} disabled={busy||choice.current!==null} onChange={e=>setCompile(e.target.checked)}/>Compile into the wiki after extraction</label><p className="small muted">Each file becomes a separate source and processing job. AI processing sends selected content to your configured provider. Follow queued jobs in Activity. Keep this window open until uploading finishes.</p>
 {error&&<p role="status" className="alert">{error}</p>}<div className="modal-footer">{busy?<button className="button secondary" onClick={()=>{stop.current=true;setError('Stopping after the current file. Queued jobs will continue.')}}>Stop after current file</button>:<button className="button secondary" onClick={onClose}>Close</button>}{!busy&&queued>0&&<button className="button secondary" onClick={onActivity}>View Activity</button>}<button className="button" disabled={busy||pending+failed===0} onClick={upload}>{busy?'Uploading…':failed?'Retry / upload remaining':`Upload ${pending} file${pending===1?'':'s'}`}</button></div></div>
}
