import {useContext} from 'react';
import {Link} from 'react-router-dom';
import {Plus,ArrowRight} from 'lucide-react';
import {Context,Heading} from './App';

export function HelpView(){
 const {add}=useContext(Context);
 return <><Heading eyebrow="A LITTLE GUIDANCE" title="Quick Guide & Help">From your first source to a wiki you can trust.</Heading>
 <section className="paper help-intro"><h2>Start with something worth remembering</h2><p>Commonplace keeps your original documents and uses AI to turn their evidence into connected wiki pages. You can always trace a citation back to its source.</p><div className="actions"><button className="button" onClick={add}><Plus size={16}/>Add a source</button><Link className="button secondary" to="/settings">Open Settings <ArrowRight size={16}/></Link></div></section>
 <section className="paper help-section"><h2>Your first wiki, step by step</h2><ol className="help-steps">
 <li><h3>Choose how to work</h3><p>For AI compilation, open <Link to="/settings">Settings</Link>, choose a provider, enter its API key and exact model name, then save. Turn on <strong>Enable external models</strong> when you are ready to send selected content to that provider. You can also keep it off and build your source library locally.</p></li>
 <li><h3>Add a source</h3><p>Click <strong>Add a source</strong> to paste text, upload a PDF, Markdown or TXT file, or import a public webpage. Leave “Compile into the wiki after extraction” checked to generate pages. Uncheck it if you only want to preserve and extract the source.</p></li>
 <li><h3>Follow the progress</h3><p>Open <Link to="/activity">Activity</Link> to see processing stages, results, and any errors. If review-first mode is enabled, inspect the proposed changes there and apply or reject them.</p></li>
 <li><h3>Read and check the evidence</h3><p>Open <Link to="/">Wiki</Link> to explore generated pages. Click a citation to read its exact quote and open the original source passage. Use page history to compare revisions; protect important pages or sections from AI edits.</p></li>
 <li><h3>Ask questions and keep learning</h3><p>Use <Link to="/research">Research</Link> to ask about your collected knowledge. Check the answer’s evidence, then use “Save to wiki” for an answer worth retaining. Run <Link to="/health">Wiki health</Link> to find issues as the library grows.</p></li>
 </ol></section>
 <div className="help-grid"><section className="paper help-section"><h2>Where to find things</h2><dl className="help-map">{[['/','Wiki','Read concept pages and their revision history.'],['/sources','Sources','Browse preserved originals and extracted passages.'],['/research','Research','Ask questions with source-backed answers.'],['/activity','Activity','Review jobs, proposed changes, errors, and usage.'],['/health','Wiki health','Check and resolve maintenance issues.'],['/settings','Settings','Manage connections, privacy controls, limits, and exports.']].map(([path,label,detail])=><div key={path}><dt><Link to={path}>{label} <ArrowRight size={13}/></Link></dt><dd>{detail}</dd></div>)}</dl></section>
 <section className="paper help-section"><h2>Privacy & control</h2><p>Your sources and wiki are stored on this computer. AI processing sends selected text to the configured provider and may incur charges.</p><p><strong>External models are off by default.</strong> Switching off blocks subsequent model requests, retries, connection tests, and OAuth requests. It cannot recall a request already sent. Importing a webpage still fetches that URL.</p><p>API keys are stored in .env and OAuth tokens in a separate private .credentials folder, outside local-data. Neither is included in knowledge backups. Local reading, editing, search, and extraction remain available while the switch is off. For an extra review step, enable <strong>Review changes before applying</strong> in Settings.</p></section></div>
 <section className="paper help-section"><h2>Common questions</h2>
 <details><summary>Why did my source not create a wiki page?</summary><p>Check Activity for the job result. Compilation requires external models to be enabled, a working connection, and a model name. Extraction alone preserves the source without generating pages. A compilation can also finish with no changes if there is nothing new to add.</p></details>
 <details><summary>What should I do when a job fails?</summary><p>Read the error in Activity. Check the selected provider’s credentials and model name in Settings. If a processing limit was reached, split the source or adjust the limit. After fixing the cause, retry the job. Your preserved source remains available.</p></details>
 <details><summary>What does “needs review” mean?</summary><p>The change is waiting for attention. Review-first mode stages proposals; protected content and conflicting edits can also prevent automatic application. Inspect the job and its proposed diff in Activity. If the page changed since the proposal was created, retry compilation against the current revision.</p></details>
 <details><summary>Can I sign in with my ChatGPT or Grok subscription?</summary><p>That sign-in integration is not available in this version. The OpenAI and Grok connections currently use API keys. Custom OAuth is for a compatible API with a registered public client, authorization URL, token URL, and API scopes; it is not a ready-made ChatGPT or Grok subscription login.</p></details>
 <details><summary>Why does my PDF have no extracted text?</summary><p>Scanned PDFs may contain only images. This version does not perform OCR. Convert the scan to a searchable PDF or text before uploading it. Encrypted or oversized files may also need preparation; Activity shows the reason.</p></details>
 <details><summary>Does a successful connection test mean AI will work?</summary><p>The test checks the provider’s model listing without sending documents. It does not verify paid inference access, available credit, or that the selected model supports the required JSON output. A real compilation or research job verifies more of the connection.</p></details>
 <details><summary>How do I back up my work?</summary><p>Settings offers a Markdown export for readable wiki pages. A full backup also needs the original sources and revision history. From the application folder, run:</p><pre><code>.venv/bin/python manage.py backup /absolute/path/commonplace-backup.zip</code></pre><p>Choose a new filename. Full backups exclude API keys and OAuth tokens. To restore into a new directory:</p><pre><code>.venv/bin/python manage.py restore /absolute/path/commonplace-backup.zip /absolute/path/new-workspace</code></pre><p>Follow the command’s instructions for selecting the restored data directory and reviewing its rules.</p></details>
 <details><summary>How do I reopen the app?</summary><p>Keep the local server running and open <a href="http://127.0.0.1:5173/">the development app</a> in Safari or another browser. After restarting your computer, run this from the application folder:</p><pre><code>.venv/bin/python start.py --dev</code></pre><p>For the built version, run <code>.venv/bin/python start.py</code> and open <a href="http://127.0.0.1:8000/">port 8000</a>. Opening the HTML file directly will not run the application.</p></details>
 </section></>
}
