import {useContext,useState,useEffect} from 'react';
import {Save,Download,ExternalLink,PlugZap,ShieldCheck} from 'lucide-react';
import {Heading,Badge,Context,useData,ErrorBox} from './App';
import {api} from './api';
import {ResetWorkspace} from './ResetWorkspace';
const docs:Record<string,string>={openrouter:'https://openrouter.ai/models',deepseek:'https://api-docs.deepseek.com/',qwen:'https://www.alibabacloud.com/help/en/model-studio/first-api-call-to-qwen',kimi:'https://platform.kimi.ai/docs/api/overview',openai:'https://platform.openai.com/docs/models',grok:'https://docs.x.ai/developers/quickstart'};
export function SettingsView(){
 const {data:s,error}=useData('/settings');const {notify,refresh}=useContext(Context);
 const [draft,setDraft]=useState<any>(null),[keys,setKeys]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[switching,setSwitching]=useState(false),[enabled,setEnabled]=useState(false),[test,setTest]=useState('');
 useEffect(()=>{if(s){setEnabled(s.external_models_enabled);if(!draft){const {key_configured,data_dir,providers,oauth_connected,oauth_redirect_uri,external_models_enabled,...values}=s;setDraft(values)}}},[s]);
 async function toggle(){setSwitching(true);try{const result=await api('/settings','PUT',{external_models_enabled:!enabled});setEnabled(result.external_models_enabled);refresh();notify(result.external_models_enabled?'External models enabled':'External models disabled')}catch(e:any){notify(e.message,true)}finally{setSwitching(false)}}
 async function persist(){await api('/settings','PUT',draft);for(const [provider,api_key] of Object.entries(keys)){if(api_key)await api('/settings/credential','POST',{provider,api_key})}setKeys({});refresh()}
 async function save(check=false){setBusy(true);setTest('');try{await persist();if(check){const result=await api('/settings/test','POST');setTest(result.message)}notify('Settings saved')}catch(e:any){notify(e.message,true);setTest(e.message)}finally{setBusy(false)}}
 async function connect(){setBusy(true);try{await persist();const result=await api('/oauth/start','POST');window.location.assign(result.authorization_url)}catch(e:any){notify(e.message,true);setBusy(false)}}
 async function disconnect(){try{await api('/oauth/disconnect','POST');refresh();notify('OAuth credentials removed locally')}catch(e:any){notify(e.message,true)}}
 if(!draft)return <ErrorBox text={error}/>;
 const selected=draft.api_provider,provider=s.providers[selected],prefix=selected==='openrouter'?'':selected+'_',modelKey=prefix?prefix+'model':'default_model',custom=selected==='custom';
 const edit=(key:string,value:any)=>setDraft({...draft,[key]:value});
 return <><Heading eyebrow="MAKE THIS WORKSPACE YOURS" title="Settings" action={<button className="button" disabled={busy||switching} onClick={()=>save()}><Save size={16}/>Save settings</button>}/>
 <section className="paper external-control" aria-label="External model protection"><div className="external-control-copy"><ShieldCheck size={24}/><div><h2>Enable external models</h2><p className="muted small">{enabled?'On: AI jobs may send selected source and wiki content to your configured provider.':'Off: model requests, connection tests, and OAuth connections are blocked by the server.'}</p></div></div><button type="button" role="switch" aria-label="Enable external models" aria-checked={enabled} disabled={switching||busy} className={'model-switch '+(enabled?'on':'')} onClick={toggle}><span/>{enabled?'On':'Off'}</button><p className="muted small external-control-note">Changes take effect immediately. Turning this off stops subsequent requests, including retries; a request already sent cannot be recalled. Local reading, editing, search, and extraction remain available. Importing a URL still fetches that URL.</p></section>
 <div className="settings-grid"><section className="paper settings-section"><div className="section-title"><h2>Model connection</h2><Badge>{custom&&draft.custom_auth==='oauth'?(s.oauth_connected?'OAuth connected':'OAuth not connected'):provider.key_configured?'Key saved':'Not connected'}</Badge></div><p className="muted small">Each provider has separate credentials and models. Custom connections use the OpenAI-compatible Chat Completions format with JSON output.</p>
 <label>API provider<select value={selected} onChange={e=>{edit('api_provider',e.target.value);setTest('')}}>{Object.entries(s.providers).map(([id,p]:any)=><option key={id} value={id}>{p.name}{id==='openrouter'?' (default)':''}</option>)}</select></label>
 {custom||selected==='qwen'?<><label>API base URL<input type="url" value={draft[selected+'_base_url']} onChange={e=>edit(selected+'_base_url',e.target.value)} placeholder="https://your-provider.example/v1"/></label><p className="muted small">{selected==='qwen'?'Use an endpoint matching your Alibaba Cloud region and workspace. The Singapore endpoint is supplied by default. ':'Enter the base URL, without /chat/completions. HTTPS or a local HTTP server is supported. '}Changing the endpoint clears its saved API key; enter a new key for the new destination.</p></>:<label>Official API endpoint<code className="path-display">{provider.base_url}</code></label>}
 {custom&&<label>Authentication<select value={draft.custom_auth} onChange={e=>edit('custom_auth',e.target.value)}><option value="api_key">API key</option><option value="oauth">OAuth 2.0 — Authorization Code + PKCE</option><option value="none">No authentication (e.g. local server)</option></select></label>}
 {(!custom||draft.custom_auth==='api_key')&&<><label>{provider.name} API key<input type="password" autoComplete="new-password" value={keys[selected]||''} onChange={e=>setKeys({...keys,[selected]:e.target.value})} placeholder={provider.key_configured?'Key saved; enter a new key to replace it':'Paste your API key'}/></label><p className="small muted">Keys are saved separately in the local .env file and are never returned by the API.</p></>}
 {(selected==='openai'||selected==='grok')&&<div className="alert"><strong>{selected==='openai'?'ChatGPT':'Grok'} subscription OAuth</strong><p>This connection uses an API key. Direct subscription OAuth is not integrated: this app has no registered subscription OAuth client. {selected==='openai'?'ChatGPT sign-in in Codex does not provide a general OpenAI API key.':'Signing into the Grok website does not provide an xAI API key.'} For a registered OAuth-enabled API or gateway, choose Custom API.</p></div>}
 {custom&&draft.custom_auth==='oauth'&&<div className="oauth-fields"><p className="small muted">Use a registered public OAuth client that supports PKCE (S256) and grants Bearer-token access to your configured model API. Login-only scopes do not grant inference access. Clients requiring a secret are not supported.</p>{[['oauth_authorize_url','Authorization URL'],['oauth_token_url','Token URL'],['oauth_client_id','Client ID'],['oauth_scope','Scopes (space-separated)'],['oauth_audience','Audience (optional)']].map(([key,label])=><label key={key}>{label}<input value={draft[key]} onChange={e=>edit(key,e.target.value)}/></label>)}<label>Register this exact redirect URI<code className="path-display">{s.oauth_redirect_uri}</code></label><p className="small muted">Open this app using 127.0.0.1 when connecting. Access and refresh tokens are stored in the private .credentials folder outside your knowledge data and excluded from backups. Changing OAuth or API endpoint settings requires reconnecting.</p><div className="actions"><button className="button secondary" disabled={busy||!enabled} onClick={connect}>Save & connect OAuth</button>{s.oauth_connected&&<button className="button secondary" disabled={busy} onClick={disconnect}>Disconnect</button>}</div></div>}
 <label>Default model<input value={draft[modelKey]} onChange={e=>edit(modelKey,e.target.value)} placeholder="Exact model identifier from your provider"/></label><details><summary>Per-role model overrides</summary>{['compiler','research','linter'].map(role=><label key={role}>{role.charAt(0).toUpperCase()+role.slice(1)} model<input value={draft[prefix+role+'_model']} onChange={e=>edit(prefix+role+'_model',e.target.value)} placeholder="Use this provider's default model"/></label>)}</details>
 <div className="actions"><button className="button secondary" disabled={busy||!enabled} onClick={()=>save(true)}><PlugZap size={16}/>Save & test connection</button>{docs[selected]&&<a className="text-link" href={docs[selected]} target="_blank" rel="noreferrer">Models & documentation <ExternalLink size={14}/></a>}</div>{test&&<div className="alert" role="status">{test}</div>}<p className="small muted" role="status">{!enabled?'Connection testing is disabled because external models are off. Turn on “Enable external models” above to test your saved credentials.':'External models are enabled. You can now save and test this connection.'}</p><p className="small muted">The connection check lists models. It does not send documents or verify paid inference access.</p></section>
 <section className="paper settings-section"><h2>Compilation behavior</h2><label className="check-row"><input type="checkbox" checked={draft.review_first} onChange={e=>edit('review_first',e.target.checked)}/>Review changes before applying</label><p className="muted small">Validated changes apply automatically by default. Protected sections and conflicts always need attention.</p><h2 className="subheading">Processing limits</h2>{[['max_calls','Maximum model calls per job'],['context_tokens','Configured model context capacity'],['max_input_tokens','Input token budget per job'],['max_output_tokens','Output token budget per job'],['max_pages','Pages changed per compilation'],['max_text_chars','Maximum extracted characters']].map(([field,label])=><label key={field}>{label}<input type="number" min="1" value={draft[field]} onChange={e=>edit(field,Number(e.target.value))}/></label>)}<p className="muted small">Input estimates conservatively use UTF-8 bytes. Actual reported usage appears in Activity. No dollar spending cap is claimed.</p></section>
 <section className="paper settings-section"><h2>Your data</h2><label>Local data directory<code className="path-display">{s.data_dir}</code></label><p className="muted small">SQLite holds committed revisions. Readable Markdown is refreshed automatically. Edit pages in the app; external edits are kept as recovery copies.</p><a className="button secondary" href="/api/export/wiki"><Download size={16}/>Export Markdown wiki</a><p className="muted small">A Markdown export is not a full backup. The included backup command also preserves originals and history.</p></section><ResetWorkspace/></div></>
}
